name: Static Analysis

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  static:
    name: Static Tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
    - name: Checkout
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

    - name: Setup PHP
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
      with:
        php-version: 8.2
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --no-progress --ansi

    - name: Style
      run: composer test:lint
