name: Tests

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.3', '8.4', '8.5']
        laravel: ['11', '12', '13']
        dependency-version: [prefer-lowest, prefer-stable]
        parallel: ['', '--parallel']

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.os }} - ${{ matrix.dependency-version }} - ${{ matrix.parallel }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip, fileinfo
          tools: composer:v2
          coverage: none

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Set Minimum PHP 8.4 Versions
        run: composer require nesbot/carbon:^3.4 --no-interaction --no-update
        if: matrix.php >= 8.4

      - name: Install PHP dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress --ansi

      - name: Unit Tests
        run: composer test:unit

      - name: Unit Options Tests
        run: composer test:unit:options
